controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_garra_ombro/Controller

    joint_state_broadcaster:
      type: joint_garra_ombro/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - base_link_to_upper_arm_r_link_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity